### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by kirshman** [Minecraft1-12-2Pi/Minecraft1.12.2#2]
whenver i run the script, I get this.  I am behind a proxy, but have entered the proxy settings and am able to download from anything else.  Do you know what I can try?

Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 2/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 3/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 4/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 5/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 6/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 7/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 8/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 9/10)
Exception: java.net.ConnectException: Connection refused
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma (try 10/10)
Exception: java.net.ConnectException: Connection refused
Unable to download remote file. Check your internet connection/proxy settings.
FATAL ERROR: net.minecraft.bootstrap.FatalBootstrapError: Unable to download while being forced
	at net.minecraft.bootstrap.Bootstrap.execute(Bootstrap.java:95)
	at net.minecraft.bootstrap.Bootstrap.main(Bootstrap.java:381)

**Comment by MinecraftDesktopOnPi** [comment]
maybe try turning the proxy off. the amazonaws site doesnt like proxies.
